baseurl = "https://www.coymcnew.com/"
languageCode = "en-us"
title = "Coy's Personal Website"
theme = "hugo-xmin"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
footnotereturnlinkcontents = "↩"

[permalinks]
    post = "/post/:year/:month/:day/:slug/"
    note = "/note/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "Posts"
    url = "/post/"
    weight = 2
[[menu.main]]
    name = "About"
    url = "/about-rmd/"
    weight = 4
[[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 5
[[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 6
#[[menu.main]]
#    name = "Subscribe"
#    url = "/index.xml"

[params]
    description = "A website built through Hugo and blogdown."
    footer = "&copy; [Coy McNew](https://www.coymcnew.com) 2020 -- 2020 | [Github](https://github.com/mcnewcp)"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
